# curl -u user:96d3c532-edc8-471b-8ac3-f80a122ff987 http://localhost:8080/hello
GET https://localhost:8080/hello
Authorization: Basic kkkkkksssssaaaa kkkkkksssssaaaa
X-IDENTIFIER: 12345

###
POST https://localhost:8080/hello
Authorization: Basic kkkkkksssssaaaa kkkkkksssssaaaa
X-IDENTIFIER: 12345
X-Csrf-Token: S92oB4FNS5baDXUAY3V_A0tk6nBUwCDgPYjK2OzG0pl0zoBOf-WYNOQsKaf3aEYyWlhLZXlSx0hj8EXNDuzz6Irw5atE-eJ-

###
GET https://localhost:8080/bye
Authorization: Basic kkkkkksssssaaaa kkkkkksssssaaaa

###
GET https://localhost:8080/ciao
Authorization: Basic kkkkkksssssaaaa kkkkkksssssaaaa

###
POST https://localhost:8080/ciao
Authorization: Basic kkkkkksssssaaaa kkkkkksssssaaaa

###
GET https://localhost:8080/hola
Authorization: SD9cICjl1e

