spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:./database/spring-security-in-action/biz;AUTO_SERVER=true
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  mvc:
    static-path-pattern: classpath:/static/**

server:
  port: 8082

auth:
  server:
    base:
      url: http://localhost:8081

jwt:
  signing:
    key: "1234"