spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:./database/spring-security-in-action/grant;AUTO_SERVER=true
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  mvc:
    static-path-pattern: classpath:/static/**
  security:
    user:
      name: user
      password: password
  main:
    allow-bean-definition-overriding: true

custom:
  default-url: http://localhost:${server.port}
  security:
    client:
      id: 14502624-340c-48ef-adfe-531b997ec670
      client-id: grant-client
      client-secret: secret
      redirect-uris:
        - ${custom.default-url}/login/oauth2/code/login-client
        - ${custom.default-url}/authorized

server:
  port: 8083
