spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:./database/spring-security-in-action/oauth;AUTO_SERVER=true
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  mvc:
    static-path-pattern: classpath:/static/**
# use spring auto config to registered github app
#  security:
#    oauth2:
#      client:
#        registration:
#          github:
#            client-id: Ov23liKuE6UNVjWP6fjb
#            client-secret: 0a057559bc6f6e07d2d756a51ac94d5f9126921e

server:
  port: 8080

auth:
  client:
    github:
      id: github
      name: Github
      keys:
        id: #
        secret: #




jwt:
  signing:
    key: "1234"